// Mocks generated by Mockito 5.4.6 from annotations
// in ugo_driver/test/driver_repository_mock_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ugo_driver/backend/api_requests/api_calls.dart' as _i2;
import 'package:ugo_driver/repositories/driver_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiCallResponse_0 extends _i1.SmartFake
    implements _i2.ApiCallResponse {
  _FakeApiCallResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DriverRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverRepositoryInterface extends _i1.Mock
    implements _i3.DriverRepositoryInterface {
  MockDriverRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiCallResponse> fetchDriverProfile({
    required String? token,
    required int? driverId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDriverProfile,
          [],
          {
            #token: token,
            #driverId: driverId,
          },
        ),
        returnValue:
            _i4.Future<_i2.ApiCallResponse>.value(_FakeApiCallResponse_0(
          this,
          Invocation.method(
            #fetchDriverProfile,
            [],
            {
              #token: token,
              #driverId: driverId,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiCallResponse>);

  @override
  _i4.Future<_i2.ApiCallResponse> fetchPostQR({
    required String? token,
    required int? driverId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPostQR,
          [],
          {
            #token: token,
            #driverId: driverId,
          },
        ),
        returnValue:
            _i4.Future<_i2.ApiCallResponse>.value(_FakeApiCallResponse_0(
          this,
          Invocation.method(
            #fetchPostQR,
            [],
            {
              #token: token,
              #driverId: driverId,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiCallResponse>);

  @override
  _i4.Future<_i2.ApiCallResponse> updateDriver({
    required int? id,
    required String? token,
    required bool? isonline,
    double? latitude,
    double? longitude,
    String? fcmToken,
    Map<String, dynamic>? extraParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDriver,
          [],
          {
            #id: id,
            #token: token,
            #isonline: isonline,
            #latitude: latitude,
            #longitude: longitude,
            #fcmToken: fcmToken,
            #extraParams: extraParams,
          },
        ),
        returnValue:
            _i4.Future<_i2.ApiCallResponse>.value(_FakeApiCallResponse_0(
          this,
          Invocation.method(
            #updateDriver,
            [],
            {
              #id: id,
              #token: token,
              #isonline: isonline,
              #latitude: latitude,
              #longitude: longitude,
              #fcmToken: fcmToken,
              #extraParams: extraParams,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiCallResponse>);

  @override
  _i4.Future<_i2.ApiCallResponse> getVehicleTypes() => (super.noSuchMethod(
        Invocation.method(
          #getVehicleTypes,
          [],
        ),
        returnValue:
            _i4.Future<_i2.ApiCallResponse>.value(_FakeApiCallResponse_0(
          this,
          Invocation.method(
            #getVehicleTypes,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiCallResponse>);

  @override
  _i4.Future<_i2.ApiCallResponse> getAllDrivers({String? token}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDrivers,
          [],
          {#token: token},
        ),
        returnValue:
            _i4.Future<_i2.ApiCallResponse>.value(_FakeApiCallResponse_0(
          this,
          Invocation.method(
            #getAllDrivers,
            [],
            {#token: token},
          ),
        )),
      ) as _i4.Future<_i2.ApiCallResponse>);

  @override
  _i4.Future<_i2.ApiCallResponse> getDriverIncentives({
    required String? token,
    required int? driverId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriverIncentives,
          [],
          {
            #token: token,
            #driverId: driverId,
          },
        ),
        returnValue:
            _i4.Future<_i2.ApiCallResponse>.value(_FakeApiCallResponse_0(
          this,
          Invocation.method(
            #getDriverIncentives,
            [],
            {
              #token: token,
              #driverId: driverId,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiCallResponse>);

  @override
  _i4.Future<_i2.ApiCallResponse> getTodayEarnings({
    required String? token,
    required int? driverId,
    String? period = 'daily',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayEarnings,
          [],
          {
            #token: token,
            #driverId: driverId,
            #period: period,
          },
        ),
        returnValue:
            _i4.Future<_i2.ApiCallResponse>.value(_FakeApiCallResponse_0(
          this,
          Invocation.method(
            #getTodayEarnings,
            [],
            {
              #token: token,
              #driverId: driverId,
              #period: period,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiCallResponse>);

  @override
  _i4.Future<_i2.ApiCallResponse> getRideHistory({
    required String? token,
    required int? driverId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRideHistory,
          [],
          {
            #token: token,
            #driverId: driverId,
          },
        ),
        returnValue:
            _i4.Future<_i2.ApiCallResponse>.value(_FakeApiCallResponse_0(
          this,
          Invocation.method(
            #getRideHistory,
            [],
            {
              #token: token,
              #driverId: driverId,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiCallResponse>);
}
