include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/custom_code/**
    - lib/flutter_flow/custom_functions.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true