include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/custom_code/**
    - lib/flutter_flow/custom_functions.dart
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    constant_identifier_names: ignore
    unnecessary_getters_setters: ignore
    avoid_function_literals_in_foreach_calls: ignore
    type_literal_in_constant_pattern: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true