/// Static fallback lists for vehicle makes (brands) and models.
/// Used when API endpoints are not available.
class VehicleData {
  static const List<String> defaultMakes = [
    'Maruti Suzuki',
    'Hyundai',
    'Tata',
    'Mahindra',
    'Honda',
    'Toyota',
    'Kia',
    'MG',
    'Ford',
    'Volkswagen',
    'Skoda',
    'Renault',
    'Nissan',
    'BMW',
    'Mercedes-Benz',
    'Audi',
    'Bajaj',
    'Hero',
    'TVS',
    'Royal Enfield',
    'Yamaha',
    'Other',
  ];

  static const List<String> defaultModels = [
    'Swift',
    'Baleno',
    'Dzire',
    'Alto',
    'Wagon R',
    'Ertiga',
    'Brezza',
    'Creta',
    'Venue',
    'i20',
    'Santro',
    'Punch',
    'Nexon',
    'Harrier',
    'Safari',
    'XUV700',
    'Scorpio',
    'Thar',
    'City',
    'Amaze',
    'Civic',
    'Fortuner',
    'Innova',
    'Innova Crysta',
    'Glanza',
    'Seltos',
    'Sonet',
    'Carens',
    'Hector',
    'EcoSport',
    'Aspire',
    'Polo',
    'Vento',
    'Rapid',
    'Kushaq',
    'Duster',
    'Kiger',
    'Magnite',
    'Kicks',
    'Pulsar',
    'Dominar',
    'Splendor',
    'Passion',
    'Apache',
    'Jupiter',
    'Classic',
    'Hunter',
    'Meteor',
    'FZ',
    'R15',
    'Ray ZR',
    'Other',
  ];
}
