// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRIJD6DFvRS7N77UFyId3uva16GhkUyD8',
    appId: '1:477734229226:web:8e6208dfa8a9fc05757393',
    messagingSenderId: '477734229226',
    projectId: 'ugo-drivers-8ff87',
    authDomain: 'ugo-drivers-8ff87.firebaseapp.com',
    storageBucket: 'ugo-drivers-8ff87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmYtUMdxt1X-x8-tQ6_Zlo5S84d8hprQA',
    appId: '1:477734229226:android:331721b39698ae65757393',
    messagingSenderId: '477734229226',
    projectId: 'ugo-drivers-8ff87',
    storageBucket: 'ugo-drivers-8ff87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB74iIzKjczDwXHSdmzI5aWmi_TenJuvhs',
    appId: '1:477734229226:ios:a1a7e001f37b816d757393',
    messagingSenderId: '477734229226',
    projectId: 'ugo-drivers-8ff87',
    storageBucket: 'ugo-drivers-8ff87.firebasestorage.app',
    iosBundleId: 'com.ugocabs.drivers',
  );

}