// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJy53wYAPtl6ij6DEOZTyn6KjUZAyCnIY',
    appId: '1:804974852515:web:e8e9c0f19ddd39e40c8216',
    messagingSenderId: '804974852515',
    projectId: 'ugo-driver-8ff43',
    authDomain: 'ugo-driver-8ff43.firebaseapp.com',
    storageBucket: 'ugo-driver-8ff43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OovgzdJ6ygvtaxSQ9VzkZzDt1t757aY',
    appId: '1:804974852515:android:ba9d7736c4cedf890c8216',
    messagingSenderId: '804974852515',
    projectId: 'ugo-driver-8ff43',
    storageBucket: 'ugo-driver-8ff43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLrJS3uG0A9Y0SsM3rIPwNW_88APksEI',
    appId: '1:804974852515:ios:6c90e9db1685e34f0c8216',
    messagingSenderId: '804974852515',
    projectId: 'ugo-driver-8ff43',
    storageBucket: 'ugo-driver-8ff43.firebasestorage.app',
    iosClientId: '804974852515-r980ua77r50331rg11qnpm2amp7ujo7u.apps.googleusercontent.com',
    iosBundleId: 'com.ugocabs.driver',
  );

}